name: ob_detect
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  camera: ^0.10.6
  permission_handler: ^11.3.1
  image: ^3.3.0
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/pothole_trained_model.tflite


